version: "3.8"

services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            # - PORT=8080 # config.json
            # - JWT_STRING=SplitWiseTestJwtSignString  # config.json
            - LOG_LEVEL=DEBUG # DEBUG, INFO, WARN, ERROR
            - DSN=host=db user=myuser password=mypassword dbname=mydb port=5432 sslmode=disable
        depends_on:
            - db
        networks:
            - splitwise-network

    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - splitwise-network

networks:
    splitwise-network:
        driver: bridge

volumes:
    pgdata:
        driver: local
